[
  {
    "ProfileName": "ErrorBased SQL Injection",
    "Name": "",
    "Enabled": true,
    "Scanner": 1,
    "Author": "@eslam3kll",
    "Payloads": [
      "true,\u0027123",
      "true,\u0027\u0027123",
      "true,`123",
      "true,\")123",
      "true,\"))123",
      "true,`)123",
      "true,`))123",
      "true,\u0027))123",
      "true,\u0027)123\"123",
      "true,[]123",
      "true,\"\"123",
      "true,\u0027\"123",
      "true,\"\u0027123",
      "true,\\123"
    ],
    "Encoder": [],
    "UrlEncode": false,
    "CharsToUrlEncode": "",
    "Grep": [
      "true,,SQL syntax.*?MySQL",
      "true,Or,Warning.*?\\Wmysqli?_",
      "true,Or,MySQLSyntaxErrorException",
      "true,Or,valid MySQL result",
      "true,Or,check the manual that (corresponds to|fits) your MySQL server version",
      "true,Or,Unknown column \u0027[^ ]+\u0027 in \u0027field list\u0027",
      "true,Or,MySqlClient\\.",
      "true,Or,com\\.mysql\\.jdbc",
      "true,Or,Zend_Db_(Adapter|Statement)_Mysqli_Exception",
      "true,Or,Pdo[./_\\\\]Mysql",
      "true,Or,MySqlException",
      "true,Or,SQLSTATE\\[\\d+\\]: Syntax error or access violation",
      "true,Or,check the manual that (corresponds to|fits) your MariaDB server version",
      "true,Or,check the manual that (corresponds to|fits) your Drizzle server version",
      "true,Or,MemSQL does not support this type of query",
      "true,Or,is not supported by MemSQL",
      "true,Or,unsupported nested scalar subselect",
      "true,Or,PostgreSQL.*?ERROR",
      "true,Or,Warning.*?\\Wpg_",
      "true,Or,valid PostgreSQL result",
      "true,Or,Npgsql\\.",
      "true,Or,PG::SyntaxError:",
      "true,Or,org\\.postgresql\\.util\\.PSQLException",
      "true,Or,ERROR:\\s\\ssyntax error at or near",
      "true,Or,ERROR: parser: parse error at or near",
      "true,Or,PostgreSQL query failed",
      "true,Or,org\\.postgresql\\.jdbc",
      "true,Or,Pdo[./_\\\\]Pgsql",
      "true,Or,PSQLException",
      "true,Or,Driver.*? SQL[\\-\\_\\ ]*Server",
      "true,Or,OLE DB.*? SQL Server",
      "true,Or,\\bSQL Server[^\u0026lt;\u0026quot;]+Driver",
      "true,Or,Warning.*?\\W(mssql|sqlsrv)_",
      "true,Or,\\bSQL Server[^\u0026lt;\u0026quot;]+[0-9a-fA-F]{8}",
      "true,Or,DB-Error.*",
      "true,Or,System\\.Data\\.SqlClient\\.SqlException\\.(SqlException|SqlConnection\\.OnError)",
      "true,Or,(?s)Exception.*?\\bRoadhouse\\.Cms\\.",
      "true,Or,Microsoft SQL Native Client error \u0027[0-9a-fA-F]{8}",
      "true,Or,\\[SQL Server\\]",
      "true,Or,ODBC SQL Server Driver",
      "true,Or,ODBC Driver \\d+ for SQL Server",
      "true,Or,SQLServer JDBC Driver",
      "true,Or,com\\.jnetdirect\\.jsql",
      "true,Or,macromedia\\.jdbc\\.sqlserver",
      "true,Or,Zend_Db_(Adapter|Statement)_Sqlsrv_Exception",
      "true,Or,com\\.microsoft\\.sqlserver\\.jdbc",
      "true,Or,Pdo[./_\\\\](Mssql|SqlSrv)",
      "true,Or,SQL(Srv|Server)Exception",
      "true,Or,Unclosed quotation mark after the character string",
      "true,Or,Microsoft Access (\\d+ )?Driver",
      "true,Or,JET Database Engine",
      "true,Or,Access Database Engine",
      "true,Or,ODBC Microsoft Access",
      "true,Or,Syntax error \\(missing operator\\) in query expression",
      "true,Or,\\bORA-\\d{5}",
      "true,Or,Oracle error",
      "true,Or,Oracle.*?Driver",
      "true,Or,Warning.*?\\W(oci|ora)_",
      "true,Or,quoted string not properly terminated",
      "true,Or,SQL command not properly ended",
      "true,Or,macromedia\\.jdbc\\.oracle",
      "true,Or,oracle\\.jdbc",
      "true,Or,Zend_Db_(Adapter|Statement)_Oracle_Exception",
      "true,Or,Pdo[./_\\\\](Oracle|OCI)",
      "true,Or,OracleException",
      "true,Or,CLI Driver.*?DB2",
      "true,Or,DB2 SQL error",
      "true,Or,\\bdb2_\\w+\\(",
      "true,Or,SQLCODE[\u003d:\\d, -]+SQLSTATE",
      "true,Or,com\\.ibm\\.db2\\.jcc",
      "true,Or,Zend_Db_(Adapter|Statement)_Db2_Exception",
      "true,Or,Pdo[./_\\\\]Ibm",
      "true,Or,DB2Exception",
      "true,Or,ibm_db_dbi\\.ProgrammingError",
      "true,Or,Warning.*?\\Wifx_",
      "true,Or,Exception.*?Informix",
      "true,Or,Informix ODBC Driver",
      "true,Or,ODBC Informix driver",
      "true,Or,com\\.informix\\.jdbc",
      "true,Or,weblogic\\.jdbc\\.informix",
      "true,Or,Pdo[./_\\\\]Informix",
      "true,Or,IfxException",
      "true,Or,Dynamic SQL Error",
      "true,Or,Warning.*?\\Wibase_",
      "true,Or,org\\.firebirdsql\\.jdbc",
      "true,Or,Pdo[./_\\\\]Firebird",
      "true,Or,SQLite/JDBCDriver",
      "true,Or,SQLite\\.Exception",
      "true,Or,(Microsoft|System)\\.Data\\.SQLite\\.SQLiteException",
      "true,Or,Warning.*?\\W(sqlite_|SQLite3::)",
      "true,Or,\\[SQLITE_ERROR\\]",
      "true,Or,SQLite error \\d+:",
      "true,Or,sqlite3.OperationalError:",
      "true,Or,SQLite3::SQLException",
      "true,Or,org\\.sqlite\\.JDBC",
      "true,Or,Pdo[./_\\\\]Sqlite",
      "true,Or,SQLiteException",
      "true,Or,SQL error.*?POS([0-9]+)",
      "true,Or,Warning.*?\\Wmaxdb_",
      "true,Or,DriverSapDB",
      "true,Or,-3014.*?Invalid end of SQL statement",
      "true,Or,com\\.sap\\.dbtech\\.jdbc",
      "true,Or,\\[-3008\\].*?: Invalid keyword or missing delimiter",
      "true,Or,Warning.*?\\Wsybase_",
      "true,Or,Sybase message",
      "true,Or,Sybase.*?Server message",
      "true,Or,SybSQLException",
      "true,Or,Sybase\\.Data\\.AseClient",
      "true,Or,com\\.sybase\\.jdbc",
      "true,Or,Warning.*?\\Wingres_",
      "true,Or,Ingres SQLSTATE",
      "true,Or,Ingres\\W.*?Driver",
      "true,Or,com\\.ingres\\.gcf\\.jdbc",
      "true,Or,Exception (condition )?\\d+\\. Transaction rollback",
      "true,Or,com\\.frontbase\\.jdbc",
      "true,Or,Syntax error 1. Missing",
      "true,Or,(Semantic|Syntax) error [1-4]\\d{2}\\.",
      "true,Or,Unexpected end of command in statement \\[",
      "true,Or,Unexpected token.*?in statement \\[",
      "true,Or,org\\.hsqldb\\.jdbc",
      "true,Or,org\\.h2\\.jdbc",
      "true,Or,\\[42000-192\\]",
      "true,Or,![0-9]{5}![^\\n]+(failed|unexpected|error|syntax|expected|violation|exception)",
      "true,Or,\\[MonetDB\\]\\[ODBC Driver",
      "true,Or,nl\\.cwi\\.monetdb\\.jdbc",
      "true,Or,Syntax error: Encountered",
      "true,Or,org\\.apache\\.derby",
      "true,Or,ERROR 42X01",
      "true,Or,, Sqlstate: (3F|42).{3}, (Routine|Hint|Position):",
      "true,Or,/vertica/Parser/scan",
      "true,Or,com\\.vertica\\.jdbc",
      "true,Or,org\\.jkiss\\.dbeaver\\.ext\\.vertica",
      "true,Or,com\\.vertica\\.dsi\\.dataengine",
      "true,Or,com\\.mckoi\\.JDBCDriver",
      "true,Or,com\\.mckoi\\.database\\.jdbc",
      "true,Or,\u0026lt;REGEX_LITERAL\u0026gt;",
      "true,Or,com\\.facebook\\.presto\\.jdbc",
      "true,Or,io\\.prestosql\\.jdbc",
      "true,Or,com\\.simba\\.presto\\.jdbc",
      "true,Or,UNION query has different number of fields: \\d+, \\d+",
      "true,Or,Altibase\\.jdbc\\.driver",
      "true,Or,com\\.mimer\\.jdbc",
      "true,Or,Syntax error,[^\\n]+assumed to mean",
      "true,Or,io\\.crate\\.client\\.jdbc",
      "true,Or,encountered after end of query",
      "true,Or,A comparison operator is required here",
      "true,Or,-10048: Syntax error",
      "true,Or,rdmStmtPrepare\\(.+?\\) returned",
      "true,Or,SQ074: Line \\d+:",
      "true,Or,SR185: Undefined procedure",
      "true,Or,SQ200: No table",
      "true,Or,Virtuoso S0002 Error",
      "true,Or,\\[(Virtuoso Driver|Virtuoso iODBC Driver)\\]\\[Virtuoso Server\\]"
    ],
    "Tags": [
      "All",
      "SQLi"
    ],
    "PayloadResponse": false,
    "NotResponse": false,
    "TimeOut1": "",
    "TimeOut2": "",
    "isTime": false,
    "contentLength": "",
    "iscontentLength": false,
    "CaseSensitive": false,
    "ExcludeHTTP": true,
    "OnlyHTTP": false,
    "IsContentType": false,
    "ContentType": "",
    "HttpResponseCode": "",
    "NegativeCT": false,
    "IsResponseCode": false,
    "ResponseCode": "",
    "NegativeRC": false,
    "urlextension": "",
    "isurlextension": false,
    "NegativeUrlExtension": false,
    "MatchType": 2,
    "Scope": 0,
    "RedirType": 1,
    "MaxRedir": 0,
    "payloadPosition": 2,
    "payloadsFile": "",
    "grepsFile": "",
    "IssueName": "Error-Based SQL Injection",
    "IssueSeverity": "High",
    "IssueConfidence": "Certain",
    "IssueDetail": "Error bases SQL Injection. To know the type of the database, search at the following source\nhttps://github.com/sqlmapproject/sqlmap/blob/master/data/xml/errors.xml",
    "RemediationDetail": "",
    "IssueBackground": "",
    "RemediationBackground": "",
    "Header": [],
    "VariationAttributes": [],
    "InsertionPointType": [
      18,
      65,
      32,
      36,
      7,
      1,
      2,
      6,
      33,
      5,
      35,
      34,
      64,
      0,
      3,
      4,
      37,
      127,
      65,
      32,
      36,
      7,
      1,
      2,
      6,
      33,
      5,
      35,
      34,
      64,
      0,
      3,
      4,
      37,
      127
    ],
    "Scanas": false,
    "Scantype": 0,
    "pathDiscovery": false
  }
]